site_name: Better with Aether
theme:
  name: material
  logo: assets/bwa.svg
  favicon: assets/bwa.svg
  palette:
    - scheme: aether
      primary: #477faa
      accent: amber
      toggle:
        icon: material/weather-night
        name: Switch to light mode
    - scheme: slate
      primary: #4682b4
      accent: amber
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  features:
    - content.code.copy
    - content.tabs
 
extra_css:
  - assets/custom.css

extra_javascript:
  - scripts.js

plugins:
  - search
  - awesome-nav

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition